- .gitignore
in order not to track the .idea folder
> .idea en gitignore

- docs/06_runtime_view.adoc
- docs/07_deployment_view.adoc
- docs/08_concepts.adoc
> Added section 8

- restapi/controllers/OrderController.ts
- restapi/interfaces/OrderInterface.ts
- restapi/interfaces/UserInterface.ts
- restapi/package-lock.json
- restapi/package.json
- restapi/repository/OrderRepository.ts
- restapi/routers/OrderRouter.ts
- restapi/schemas/OrderSchema.ts
- restapi/server.ts
Implemented Order CRUD API calls. Closing #33 .
> Backend order crud

- restapi/controllers/OrderController.ts
- restapi/controllers/ProductController.ts
- restapi/controllers/SellerController.ts
- restapi/interfaces/SellerInterface.ts
- restapi/repository/OrderRepository.ts
- restapi/repository/ProductRepository.ts
- restapi/repository/SellerRepository.ts
- restapi/routers/OrderRouter.ts
- restapi/routers/ProductRouter.ts
- restapi/routers/SellerRouter.ts
- restapi/schemas/ProductSchema.ts
- restapi/schemas/SellerSchema.ts
Moved product add and delete to seller, redisigned seller product array to use ids instead of embeds
> Backend standarize and add product

- .gitignore
- restapi/geocoder/geocoder.ts
- restapi/package-lock.json
- restapi/package.json
- restapi/server.ts
moving on we will need a .env file to be able to run the restapi, in the .env we need to add DB_NAME, DB_USERNAME, DB_PASSWORD, and PRICE_PER_KM, the PORT is also needed
> moved info to .env file, also finished price calculation based on address

- docs/01_introduction_and_goals.adoc
- docs/03_system_scope_and_context.adoc
- docs/05_building_block_view.adoc
- docs/07_deployment_view.adoc
- docs/08_concepts.adoc
- docs/09_design_decisions.adoc
- docs/11_technical_risks.adoc
We are lacking the original source files for most of the diagrams. As such, I can only update the text for now. Closes #61 .
> Docs update 2

- restapi/controllers/ProductController.ts
- restapi/routers/ProductRouter.ts
- webapp/package-lock.json
- webapp/package.json
- webapp/src/App.tsx
- webapp/src/components/listProducts/product/CartProduct.tsx
- webapp/src/helpers/getProduct.ts
- webapp/src/pages/DetailsView/DetailsView.tsx
- webapp/src/pages/DetailsView/sections/ProductImage.tsx
- webapp/src/pages/DetailsView/sections/ProductInfo.tsx
-Added 'product details' button to each listed item with 'product details' page
-Ability to add items to cart from 'product details' page
> Product details paging

- webapp/src/components/footer/CartFooter.tsx
Checkout button disabled if user is not logged in with its pod.
> Updated checkout button.

- restapi/geocoder/geocoder.ts
- webapp/src/components/Order.tsx
- webapp/src/helpers/calculate.ts
> Added shipping costs

- .github/workflows/asw2122.yml
Title. Linked to #70 and #77 .
> Factorized .env to asw2122.yml for webapp and restapi

- webapp/src/components/login/LoginButtonComponent.tsx
- webapp/src/components/logout/LogoutButtonComponent.tsx
- webapp/src/helpers/getData.ts
- webapp/src/helpers/postData.ts
- webapp/src/pages/DetailsView/DetailsView.tsx
> Refactored localhost calls to include host parameter

- .github/workflows/asw2122.yml
- restapi/server.ts
- webapp/Dockerfile
Moving environment arguments to the seemingly correct place on the github actions yml file.
> Deployment arguments

- .github/workflows/asw2122.yml
- webapp/src/components/NavBar.tsx
Deployment is now done. Closes #77 .
> Deployment arguments ok

- webapp/src/components/checkout/Form.tsx
- webapp/src/components/order/Order.tsx
- webapp/src/helpers/calculate.ts
- webapp/src/pages/Checkout.tsx
Dynamic calculation of shipping costs.
> Dynamic calculation of shipping costs.

- webapp/src/App.tsx
- webapp/src/_test_/NavBar.test.tsx
- webapp/src/_test_/Navigation.test.tsx
- webapp/src/components/Home.tsx
- webapp/src/components/NavBar.tsx
- webapp/src/components/Navigation.tsx
- webapp/src/components/login/LoginButtonComponent.tsx
- webapp/src/components/logout/LogoutButtonComponent.tsx
- webapp/src/shared/shareddtypes.ts
I have refactored the NavBar to material UI in order to focus in one component technology. In addition the login piece of code has been moved to a more suitable place in App.tsx
> NavBar refactored to material ui

- restapi/controllers/userController.ts
there was a typo on the user addition logic, i fixed it.
> user add fixed

- .github/workflows/asw2122.yml
- restapi/server.ts
- restapi/solid/solidCommunityFetch.ts
> Cors config

- webapp/src/components/userAuthentication/SelectProviderComponent.tsx
Select provider sign up tweaks.
> Select provider sign up tweaks.

- webapp/src/hooks/usePodData.tsx
from RESTAPI_URI to REACT_APP_API_URI
> process.env.REACT_APP_API_URI set

- webapp/src/hooks/useShipping.tsx
Fixing restapi url in shipping
> Fixing restapi url in shipping
